apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: config
spec:
  rules:
  - host: config.k8s.com
    http:
      paths:
      - path: /
        backend:
          serviceName: config
          servicePort: 8888
---
kind: Service
apiVersion: v1
metadata:
  name: config
spec:
  type: ClusterIP
  selector:
    app: spring-cloud-config
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-config
  labels:
    app: spring-cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-config
  template:
    metadata:
      labels:
        app: spring-cloud-config
        version: latest
    spec:
      hostname: config
      subdomain: config
      containers:
      - name: spring-cloud-config
        image: hubtea/spring-cloud-config:latest
        ports:
        - name: http
          containerPort: 8888
